<a href="https://colab.research.google.com/github/BramanTyamahedrawan/Machine-Learning-SMT-5/blob/main/pertemuan-9/Tugas_Praktikum_ANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

KELOMPOK 2
1. Braman Tyamahendrawan (04)
2. Dimas Putra Anhar W.A. (05)
3. Fikril Hadad Ramadhani (07)
4. Muhammad Maulana Givari (18)
5. Muhammad Sabilar Rosyad (19)
6. Satria Yudhistira Yudha P. (26)

# Import Library

In [1]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
import matplotlib.pyplot as plt

# Muat data MNIST

In [2]:
mnist = keras.datasets.mnist
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

11490434/11490434 [==============================] - 1s 0us/step


# Pra Pengolahan Data

In [3]:
train_images = train_images.reshape(-1, 28*28)
test_images = test_images.reshape(-1, 28*28)

In [4]:
train_images = train_images / 255.0
test_images = test_images / 255.0

# Arsitektur ANN

In [5]:
model = keras.Sequential([
    layers.Dense(128, activation='relu', input_shape=(784,)),
    layers.Dense(64, activation='relu'),
    layers.Dense(10, activation='softmax')
])

# Kompilasi Model

In [6]:
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])


# Pelatihan Model

In [7]:
model.fit(train_images, train_labels, epochs=10, validation_split=0.2)

Epoch 1/10
1500/1500 [==============================] - 13s 7ms/step - loss: 0.2667 - accuracy: 0.9212 - val_loss: 0.1381 - val_accuracy: 0.9581
Epoch 2/10
1500/1500 [==============================] - 7s 5ms/step - loss: 0.1118 - accuracy: 0.9660 - val_loss: 0.1027 - val_accuracy: 0.9701
Epoch 3/10
1500/1500 [==============================] - 8s 5ms/step - loss: 0.0760 - accuracy: 0.9764 - val_loss: 0.0848 - val_accuracy: 0.9734
Epoch 4/10
1500/1500 [==============================] - 6s 4ms/step - loss: 0.0563 - accuracy: 0.9819 - val_loss: 0.0886 - val_accuracy: 0.9739
Epoch 5/10
1500/1500 [==============================] - 9s 6ms/step - loss: 0.0443 - accuracy: 0.9853 - val_loss: 0.1014 - val_accuracy: 0.9705
Epoch 6/10
1500/1500 [==============================] - 14s 9ms/step - loss: 0.0362 - accuracy: 0.9885 - val_loss: 0.0914 - val_accuracy: 0.9752
Epoch 7/10
1500/1500 [==============================] - 7s 5ms/step - loss: 0.0295 - accuracy: 0.9904 - val_loss: 0.1053 - val_accurac

# Evaluasi Model

In [8]:
test_loss, test_accuracy = model.evaluate(test_images, test_labels)
print("Test accuracy: {:.4f}".format(test_accuracy))

313/313 [==============================] - 1s 2ms/step - loss: 0.0979 - accuracy: 0.9761
Test accuracy: 0.9761


# Confusion Matrix

In [9]:
from sklearn.metrics import confusion_matrix

predicted_labels = model.predict(test_images)
predicted_labels = [tf.argmax(label).numpy() for label in predicted_labels]

confusion = confusion_matrix(test_labels, predicted_labels)
print(confusion)

313/313 [==============================] - 1s 2ms/step
[[ 969    1    1    1    0    0    2    1    3    2]
 [   0 1124    4    1    0    0    3    0    3    0]
 [   3    0 1012    6    1    0    0    5    5    0]
 [   0    0    3  979    0   11    0    5   12    0]
 [   1    0    4    0  941    2    3    5    1   25]
 [   2    0    0   13    0  863    3    0    9    2]
 [   6    2    1    1    5    3  936    0    4    0]
 [   0    5    6    4    0    0    0 1005    2    6]
 [   1    0    5    6    1    2    1    7  949    2]
 [   2    2    0    5    4    5    0    4    4  983]]


# Hasil Yang Saya Dapatkan

**Konfigurasi model**

*   Pra Pengolahan Data: Citra-citra dari dataset MNIST dilatih setelah diubah menjadi vektor 1D dan dinormalisasi agar berada dalam rentang 0 hingga 1.

**Arsitektur ANN:**

*   Hidden layer pertama memiliki 128 unit dengan aktivasi ReLU.

*   Hidden layer kedua memiliki 64 unit dengan aktivasi ReLU.

*   Output layer memiliki 10 unit (sesuai dengan jumlah kelas digit) dengan aktivasi softmax.

*   Model menggunakan arsitektur ANN dengan tiga lapisan, yaitu satu lapisan input, dua lapisan tersembunyi, dan satu lapisan output.

*   Input layer memiliki 784 unit (28x28 piksel) dan fungsi aktivasi ReLU.


**Pelatihan Model:**

*   Hasil: Model mencapai akurasi sekitar 97.56% pada data pengujian, yang menunjukkan kemampuan yang sangat baik dalam mengklasifikasikan digit-digit MNIST.


*   Model dilatih selama 10 epoch dengan menggunakan optimizer 'adam', loss function 'sparse_categorical_crossentropy' (karena ini adalah masalah klasifikasi multikelas), dan metrik akurasi.